---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rhdh-visual-qontract-provider
  labels:
    app: rhdh-visual-qontract-provider
    app.kubernetes.io/component: rhdh-visual-qontract-provider
    app.kubernetes.io/instance: rhdh-visual-qontract-provider
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/evanshortiss/rhdh-visual-qontract-provider
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: Service
apiVersion: v1
metadata:
  name: rhdh-visual-qontract-provider
  labels:
    app: rhdh-visual-qontract-provider
    app.kubernetes.io/component: rhdh-visual-qontract-provider
    app.kubernetes.io/instance: rhdh-visual-qontract-provider
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: rhdh-visual-qontract-provider
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rhdh-visual-qontract-provider
  labels:
    app: rhdh-visual-qontract-provider
    app.kubernetes.io/component: rhdh-visual-qontract-provider
    app.kubernetes.io/instance: rhdh-visual-qontract-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: rhdh-visual-qontract-provider
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: rhdh-visual-qontract-provider
    spec:
      containers:
        - name: rhdh-visual-qontract-provider
          image: >-
            quay.io/evanshortiss/rhdh-visual-qontract-provider
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: HOMEPAGE_LINKS_JSON_PATH
              value: "/etc/data/home.json"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
