name: Build Node.js Container
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
    
      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build using Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.QUAY_ORG }}/rhdh-visual-qontract-provider
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Push Image to quay.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
